# -*- coding: utf-8 -*-
"""Tanya_DS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAdk5a5yyBc2tlCYLtXYlxYr7SJZRH-O
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/national-family-health-survey .csv')

df.head(30)

df.shape

# STEP 1: MISSING VALUE SUMMARY

missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({'Missing Values': missing, 'Percentage': missing_pct})

# Show top columns with missing values
# Show all columns that have any missing values
missing_df[missing_df['Missing Values'] > 0]

"""Thus there are no missing values"""

# STEP 2: SPLIT BY YEAR

df_1415 = df[df['year'] == '2014-15'].copy()
df_1920 = df[df['year'] == '2019-20'].copy()

print("2014-15 shape:", df_1415.shape)
print("2019-20 shape:", df_1920.shape)

# STEP 3: CORRELATION HEATMAP FOR EACH YEAR

import seaborn as sns
import matplotlib.pyplot as plt

# Select useful numeric health-related columns
health_vars = [
    'tobaco_women_15', 'tobaco_men_15',
    'alcohol_women_15', 'alcohol_men_15',
    'oral_cancer', 'cerv_cancer', 'breast_cancer',
    'men_bp_mild', 'men_bp_sev', 'men_bp_ele_med',
    'pop_f_6_sch', 'pop_below_15', 'sex_ratio_tot_pop'
]

# Function to plot heatmap
def plot_corr(data, title):
    corr = data[health_vars].corr()
    plt.figure(figsize=(10, 8))
    sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", square=True)
    plt.title(title)
    plt.tight_layout()
    plt.show()

# Plot for each year
plot_corr(df_1415, "Correlation Heatmap - 2014-15")
plot_corr(df_1920, "Correlation Heatmap - 2019-20")

# Choose your year’s dataframe and health variables
data = df_1920  # or df_1415 if you want 2014–15
vars_of_interest = [
    'tobaco_women_15', 'tobaco_men_15',
    'alcohol_women_15', 'alcohol_men_15',
    'oral_cancer', 'cerv_cancer', 'breast_cancer',
    'men_bp_mild', 'men_bp_sev', 'men_bp_ele_med',
    'pop_f_6_sch', 'pop_below_15', 'sex_ratio_tot_pop'
]

# Compute correlation matrix
corr_matrix = data[vars_of_interest].corr()

# Flatten the matrix and filter duplicates + self-correlations
corr_pairs = corr_matrix.unstack().reset_index()
corr_pairs.columns = ['Feature 1', 'Feature 2', 'Correlation']

# Remove self-pairs and duplicates
filtered = corr_pairs[corr_pairs['Feature 1'] != corr_pairs['Feature 2']]
filtered = filtered.drop_duplicates(subset=['Correlation'])

# Sort by absolute correlation value
strong_corrs = filtered.reindex(filtered['Correlation'].abs().sort_values(ascending=False).index)

# Show top 15
strong_corrs.head(15)

"""1)men_bp_mild & men_bp_ele_med0.94Very strong link: districts with more men having mildly high BP also have more men on medication for elevated BP. Obvious, but confirms progression

2️)men_bp_sev & men_bp_ele_med0.89Severe BP correlates strongly with medical intervention. Again, expected — but helps confirm data quality.

3️)cerv_cancer & breast_cancer0.84Strong: districts with high cervical cancer rates also see high breast cancer. Female health issues cluster. Possibly due to poor awareness or screening.

4️)men_bp_mild & men_bp_sev0.79Mild and severe BP rise together in regions — likely poor health management.

5️)alcohol_women_15 & alcohol_men_150.74Strong social/cultural indicator. Districts where men drink more, women often do too. Shared norms.

6️)tobaco_women_15 & tobaco_men_150.67Similar story: where tobacco use is culturally accepted, both genders show high use

7️)tobaco_men_15 & pop_below_150.51🔥 Interesting: more tobacco use where child population is higher? Could signal less education/awareness or socio-economic burden. Worth investigating

.8️)men_bp_ele_med & pop_below_15-0.47Inverse: districts with younger populations have fewer people on BP meds (likely because BP issues rise with age)

.9️)pop_f_6_sch & pop_below_15-0.46Educated districts → fewer children. Logical: education correlates with lower birthrates.

10)tobaco_men_15 & men_bp_ele_med-0.44🚩 Surprisingly inverse — maybe tobacco-heavy districts don’t access BP medication? Could be poor healthcare access.

1️1)men_bp_mild & pop_below_15-0.40Fewer mild BP cases in districts with high child population (again, younger populations = healthier BP)

.1️2)lcohol_men_15 & men_bp_ele_med0.39Clear pattern: more male alcohol use → more men on BP medication.

13)alcohol_men_15 & men_bp_mild0.39Same as above — early BP impact visible even at mild levels.

14)alcohol_men_15 & men_bp_sev0.39Alcohol might be a direct or contributing factor to worsening BP

15)oral_cancer & cerv_cancer0.36Weak-moderate link — suggests districts with poor screening or healthcare may miss both. Not biologically related, but signals systemic issue.
"""

# STEP 5: STATE-WISE MEANS FOR 2019–20

# Choose columns of interest
cols = [
    'state_name',
    'tobaco_men_15', 'tobaco_women_15',
    'alcohol_men_15', 'alcohol_women_15',
    'oral_cancer', 'breast_cancer', 'cerv_cancer',
    'men_bp_mild', 'men_bp_sev', 'men_bp_ele_med',
    'pop_f_6_sch'
]

# Group and calculate mean per state
state_summary_1920 = df_1920[cols].groupby('state_name').mean().sort_values('tobaco_men_15', ascending=False)

# Display top 10 states by male tobacco use
state_summary_1920.head(10)

# Filter states with BOTH high tobacco and high oral cancer
high_tob_cancer = state_summary_1920[
    (state_summary_1920['tobaco_men_15'] > 40) &
    (state_summary_1920['oral_cancer'] > 0.5)
].sort_values('oral_cancer', ascending=False).reset_index()

# Plot
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
sns.barplot(data=high_tob_cancer, x='state_name', y='oral_cancer', color='crimson')
plt.xticks(rotation=45)
plt.title("States with High Tobacco Use and High Oral Cancer (2019–20)")
plt.ylabel("Oral Cancer Rate (%)")
plt.xlabel("State")
plt.tight_layout()
plt.show()

# Scatter plot to see inverse relationship (if any)
plt.figure(figsize=(8,6))
sns.scatterplot(data=state_summary_1920, x='pop_f_6_sch', y='oral_cancer')
plt.title("Female Education vs Oral Cancer")
plt.xlabel("Female Population (Age 6+) in School (%)")
plt.ylabel("Oral Cancer Rate (%)")
plt.grid(True)
plt.show()

sns.scatterplot(data=state_summary_1920, x='alcohol_men_15', y='men_bp_sev')
plt.title("Alcohol Consumption vs Severe Blood Pressure (Men)")
plt.xlabel("Alcohol Use (%)")
plt.ylabel("Severe BP Cases (%)")
plt.grid(True)
plt.show()

"""##COMPARING CORRELATIONS"""

# STEP 6A - Compare same pair correlations across years

# 1. Define health variables
health_vars = [
    'tobaco_women_15', 'tobaco_men_15',
    'alcohol_women_15', 'alcohol_men_15',
    'oral_cancer', 'cerv_cancer', 'breast_cancer',
    'men_bp_mild', 'men_bp_sev', 'men_bp_ele_med',
    'pop_f_6_sch', 'pop_below_15', 'sex_ratio_tot_pop'
]

# 2. Compute correlation matrices for each year
corr_1415 = df_1415[health_vars].corr()
corr_1920 = df_1920[health_vars].corr()

# 3. Flatten the matrices
flat_1415 = corr_1415.unstack().reset_index()
flat_1920 = corr_1920.unstack().reset_index()
flat_1415.columns = ['Feature 1', 'Feature 2', 'Correlation_1415']
flat_1920.columns = ['Feature 1', 'Feature 2', 'Correlation_1920']

# 4. Merge and filter duplicates and self-pairs
merged = pd.merge(flat_1415, flat_1920, on=['Feature 1', 'Feature 2'])
merged = merged[merged['Feature 1'] != merged['Feature 2']]
merged = merged.drop_duplicates(subset=['Feature 1', 'Feature 2'])

# 5. Calculate delta correlation
merged['Δ Correlation'] = merged['Correlation_1920'] - merged['Correlation_1415']

# 6. Sort by largest absolute shift
comparison_table = merged.sort_values(by='Δ Correlation', key=abs, ascending=False)

# 7. Show top shifts
comparison_table.head(20)

# STEP 6B - Region-wise correlation matrix (Northeast India)

# Define NE states (adjust as needed)
ne_states = [
    'Assam', 'Manipur', 'Mizoram', 'Nagaland',
    'Tripura', 'Meghalaya', 'Arunachal Pradesh'
]

# Filter dataset for NE states
ne_data = df_1920[df_1920['state_name'].isin(ne_states)]

# Use same health variable list as before
health_vars = [
    'tobaco_women_15', 'tobaco_men_15',
    'alcohol_women_15', 'alcohol_men_15',
    'oral_cancer', 'cerv_cancer', 'breast_cancer',
    'men_bp_mild', 'men_bp_sev', 'men_bp_ele_med',
    'pop_f_6_sch', 'pop_below_15', 'sex_ratio_tot_pop'
]

# Compute correlation matrix
ne_corr = ne_data[health_vars].corr()

# Plot heatmap
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))
sns.heatmap(ne_corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Northeast India - Health Variable Correlation (2019–20)")
plt.tight_layout()
plt.show()

"""#Checking for sign flips from 14-15 to 19-20"""

merged.head()

merged = merged.dropna(subset=['Correlation_1415', 'Correlation_1920'])

merged['Δ Correlation'] = merged['Correlation_1920'] - merged['Correlation_1415']
merged['Sign Flip'] = (merged['Correlation_1415'] * merged['Correlation_1920']) < 0

print("Total sign flips:", merged['Sign Flip'].sum())

# Show top pairs with biggest changes
merged['Δ Correlation'] = merged['Correlation_1920'] - merged['Correlation_1415']
merged['Change Magnitude'] = merged['Δ Correlation'].abs()

merged.sort_values('Change Magnitude', ascending=False).head(10)

"""#Plotting highest correlation delta"""

x = 'pop_f_6_sch'
y = 'pop_below_15'

fig, axs = plt.subplots(1, 2, figsize=(14, 6))

sns.scatterplot(data=df_1415, x=x, y=y, ax=axs[0])
axs[0].set_title(f'2014-15: {x} vs {y}')

sns.scatterplot(data=df_1920, x=x, y=y, ax=axs[1])
axs[1].set_title(f'2019-20: {x} vs {y}')

plt.tight_layout()
plt.show()

"""In 2014–15, there was a strong negative correlation between female schooling (pop_f_6_sch) and the percentage of population below age 15, meaning that as more girls attended school, birth rates were lower—indicating effective awareness and family planning. However, by 2019–20, while the overall trend remained negative, the correlation had weakened. The data points became more scattered, suggesting that female education alone no longer explained birth rate patterns as strongly, likely due to the influence of additional social, economic, or healthcare factors over time."""

vars_to_check = [
    'pop_below_15', 'pop_f_6_sch', 'tobaco_men_15',
    'alcohol_men_15', 'oral_cancer', 'men_bp_sev'
]

for target in vars_to_check:
    for col in ['birth_rate', 'death_rate']:
        if col in df_1920.columns:
            corr = df_1920[[col, target]].corr().iloc[0, 1]
            print(f"{col} ↔ {target}: correlation = {corr:.2f}")

fertility_cols = [
    'births_5yrs_hgh_order', 'fem_15_19_pregnant', 'pop_below_15'
]

death_cols = ['deaths_last_3years']

selected_cols = fertility_cols + death_cols + [
    'pop_f_6_sch', 'fem_below24_married_before18',
    'tobaco_men_15', 'alcohol_men_15',
    'oral_cancer', 'men_bp_sev'
]

corr_df = df[selected_cols].dropna()
corr_matrix = corr_df.corr()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix: Fertility & Death vs Key Features")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Drop missing values from both columns
plot_df = df[['fem_15_19_pregnant', 'fem_below24_married_before18']].dropna()

# Create the scatter plot
plt.figure(figsize=(8, 6))
sns.scatterplot(data=plot_df, x='fem_below24_married_before18', y='fem_15_19_pregnant')

plt.title('Relationship between Early Marriage and Teen Pregnancy')
plt.xlabel('Women Married Before 18 (Below Age 24)')
plt.ylabel('Pregnant Women (Age 15-19)')
plt.grid(True)
plt.tight_layout()
plt.show()

non_numeric_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()
print("\nNon-numeric columns:")
print(non_numeric_cols)

from sklearn.preprocessing import LabelEncoder

# Convert 'year' to numeric (if not already)
df['year'] = pd.to_numeric(df['year'], errors='coerce')

# Drop 'district_name' since it's an identifier
df.drop(columns=['district_name'], inplace=True)

# Encode 'state_name'
le = LabelEncoder()
df['state_name'] = le.fit_transform(df['state_name'])

print("✅ Encoded 'state_name', dropped 'district_name', converted 'year'.")
print(df[['year', 'state_name']].head())

target = 'fem_15_19_pregnant'

if df[target].dtype == 'object' or df[target].nunique() <= 10:
    print("Target seems categorical, checking balance:")
    print(df[target].value_counts(normalize=True) * 100)
else:
    print("Target seems continuous — balancing not needed.")
    df[target].hist(bins=20)

# check top correlated numeric features with the target
corr = df.corr(numeric_only=True)[target].sort_values(ascending=False)
print("Top correlated features with target:")
print(corr.head(10))

"""#MODEL"""

from sklearn.model_selection import train_test_split

# Define predictor lists
# Simple regression: strongest single correlation
simple_predictor = ['fem_below24_married_before18']

# Multiple regression: top meaningful correlated variables
predictors = [
    'fem_below24_married_before18',
    'fp_pill',
    'pop_below_15',
    'child_5_underweight',
    'wom_preg_15_49_anaemic'
]

target = 'fem_15_19_pregnant'

# --- Simple Linear Regression split ---
X_simple = df[simple_predictor].dropna()
y_simple = df.loc[X_simple.index, target]

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X_simple, y_simple, test_size=0.2, random_state=42)
print("✅ Simple Regression Shapes:", X_train_s.shape, y_train_s.shape)

# --- Multiple Linear Regression split ---
X_multi = df[predictors].dropna()
y_multi = df.loc[X_multi.index, target]

X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(X_multi, y_multi, test_size=0.2, random_state=42)
print("✅ Multiple Regression Shapes:", X_train_m.shape, y_train_m.shape)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Initialize model
simple_lr = LinearRegression()

# Train the model
simple_lr.fit(X_train_s, y_train_s)

# Predict on test data
y_pred_s = simple_lr.predict(X_test_s)

# Evaluate
r2_s = r2_score(y_test_s, y_pred_s)
rmse_s = np.sqrt(mean_squared_error(y_test_s, y_pred_s))

print("📈 Simple Linear Regression Results")
print("----------------------------------")
print(f"Intercept: {simple_lr.intercept_:.3f}")
print(f"Coefficient: {simple_lr.coef_[0]:.3f}")
print(f"R² Score (Test): {r2_s:.3f}")
print(f"RMSE (Test): {rmse_s:.3f}")

# Visualize
plt.figure(figsize=(7,5))
sns.scatterplot(x=X_test_s.iloc[:,0], y=y_test_s, label='Actual', alpha=0.7)
sns.lineplot(x=X_test_s.iloc[:,0], y=y_pred_s, color='red', label='Predicted')
plt.xlabel('fem_below24_married_before18')
plt.ylabel('fem_15_19_pregnant')
plt.title('Simple Linear Regression')
plt.legend()
plt.tight_layout()
plt.show()

"""A simple linear regression was performed using the percentage of women married before age 18 (fem_below24_married_before18) to predict the percentage of teenage pregnancies (fem_15_19_pregnant) across districts.

The model yielded an intercept of 0.37 and a slope coefficient of 0.29. This implies that for every 1% rise in early marriages, the teen pregnancy rate increases by approximately 0.29%.

The model achieved an R² score of 0.447, indicating that early marriage alone explains about 45% of the variation in teenage pregnancy rates. Although this is a moderately strong relationship, it suggests that other social, economic, or health-related factors also play significant roles.

The RMSE of 3.5% suggests moderate predictive accuracy — average predictions deviate from actual teen pregnancy rates by roughly 3.5 percentage points.

Overall, these results provide empirical support for the hypothesis that early marriage is a strong driver of adolescent pregnancy in India, aligning with both prior NFHS findings and literature in public health demographics.

#MULTIPLE LINEAR REGRESSION
"""

# Predictors for multiple regression
predictors = [
    'fem_below24_married_before18',
    'fp_pill',
    'pop_below_15',
    'child_5_underweight',
    'wom_preg_15_49_anaemic'
]
target = 'fem_15_19_pregnant'

X_multi = df[predictors].dropna()
y_multi = df.loc[X_multi.index, target]

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

multi_lr = LinearRegression()
multi_lr.fit(X_multi, y_multi)
y_pred_m = multi_lr.predict(X_multi)

r2_m = r2_score(y_multi, y_pred_m)
rmse_m = np.sqrt(mean_squared_error(y_multi, y_pred_m))

print("📊 Multiple Linear Regression Results")
print("-----------------------------------")
print("Intercept:", round(multi_lr.intercept_,3))
print("Coefficients:")
for name, coef in zip(predictors, multi_lr.coef_):
    print(f"{name}: {coef:.3f}")
print(f"R² (Overall): {r2_m:.3f}")
print(f"RMSE: {rmse_m:.3f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Predicted vs Actual
plt.figure(figsize=(7,5))
sns.scatterplot(x=y_multi, y=y_pred_m, alpha=0.7)
plt.plot([y_multi.min(), y_multi.max()], [y_multi.min(), y_multi.max()], color='red', linestyle='--')
plt.xlabel("Actual Teen Pregnancy (%)")
plt.ylabel("Predicted Teen Pregnancy (%)")
plt.title("📊 Multiple Linear Regression: Actual vs Predicted")
plt.tight_layout()
plt.show()

residuals = y_multi - y_pred_m

plt.figure(figsize=(7,5))
sns.scatterplot(x=y_pred_m, y=residuals, alpha=0.6)
plt.axhline(0, color='red', linestyle='--')
plt.xlabel("Predicted Teen Pregnancy (%)")
plt.ylabel("Residual (Actual - Predicted)")
plt.title("Residual Plot – Checking Model Fit")
plt.tight_layout()
plt.show()

coef_df = pd.DataFrame({
    'Feature': predictors,
    'Coefficient': multi_lr.coef_
}).sort_values(by='Coefficient', ascending=False)

plt.figure(figsize=(8,5))
sns.barplot(x='Coefficient', y='Feature', data=coef_df, palette='coolwarm')
plt.title("Feature Importance – Multiple Linear Regression Coefficients")
plt.tight_layout()
plt.show()

"""Adding 4 additional predictors improved R² from 0.447 → 0.587

RMSE reduced from 3.50 → 3.30

So the model now fits ~30% better overall.

#CLUSTERING
"""

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

features_behavioral = [
    'tobaco_men_15',
    'alcohol_men_15',
    'men_bp_sev',
    'tobaco_women_15',
    'alcohol_women_15',
    'oral_cancer',
    'cerv_cancer'
]

Xb = df[features_behavioral].dropna()
scaler = StandardScaler()
Xb_scaled = scaler.fit_transform(Xb)

sil = []
K = range(2, 8)

for k in K:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(Xb_scaled)
    sil.append(silhouette_score(Xb_scaled, labels))

plt.plot(K, sil, 'o-', color='teal')
plt.title('Silhouette Score vs Cluster Count')
plt.xlabel('k')
plt.ylabel('Silhouette Score')
plt.show()

best_k = K[sil.index(max(sil))]
print("✅ Best k =", best_k)

kmeans_b = KMeans(n_clusters=best_k, random_state=42, n_init=20)
labels_b = kmeans_b.fit_predict(Xb_scaled)
Xb['cluster'] = labels_b

cluster_centers_b = pd.DataFrame(
    scaler.inverse_transform(kmeans_b.cluster_centers_),
    columns=features_behavioral
)
print(cluster_centers_b.round(2))

from sklearn.decomposition import PCA
pca = PCA(n_components=2, random_state=42)
Xb_pca = pca.fit_transform(Xb_scaled)

plt.figure(figsize=(7,6))
plt.scatter(Xb_pca[:,0], Xb_pca[:,1], c=labels_b, cmap='plasma', alpha=0.7)
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.title('Behavioral & Health Risk Clusters')
plt.colorbar(label='Cluster')
plt.show()

"""Step 6: Check if health outcomes differ across clusters

We can test if cancer prevalence or BP severity differs significantly among clusters.
"""

from scipy.stats import f_oneway

for var in ['oral_cancer', 'cerv_cancer', 'men_bp_sev']:
    groups = [Xb[Xb.cluster==c][var] for c in sorted(Xb.cluster.unique())]
    f, p = f_oneway(*groups)
    print(f"{var}: F={f:.2f}, p={p:.4f}")

import seaborn as sns
import matplotlib.pyplot as plt

cluster_centers_b = pd.DataFrame(
    scaler.inverse_transform(kmeans_b.cluster_centers_),
    columns=features_behavioral
)
plt.figure(figsize=(8,5))
sns.heatmap(cluster_centers_b, annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Cluster Profiles – Behavioral & Health Risk Factors")
plt.xlabel("Variables")
plt.ylabel("Cluster")
plt.show()

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score, KFold
X = df[predictors].dropna()
y = df.loc[X.index, 'fem_15_19_pregnant']

rf = RandomForestRegressor(n_estimators=200, random_state=42)
cv = KFold(n_splits=5, shuffle=True, random_state=42)
print("CV R2:", cross_val_score(rf, X, y, cv=cv, scoring='r2').mean())
rf.fit(X, y)
importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
print(importances)

df=pd.read_csv('/content/national-family-health-survey .csv')
# Aggregate to state means (replace 'state' with your state column name)
state_df = df.groupby('state_name')[features_behavioral + [
    'fem_below24_married_before18','fem_15_19_pregnant']].mean().dropna()

# Standardize and cluster
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
scaler = StandardScaler()
S = scaler.fit_transform(state_df)
k = 3
km = KMeans(n_clusters=k, random_state=42, n_init=20).fit(S)
state_df['cluster'] = km.labels_

# Visualize
state_df[['cluster', 'fem_15_19_pregnant']].sort_values('cluster')

"""WOMENS EMPOWERMENT CLUSTERING"""

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

features_empower = [
    'pop_f_6_sch',  # female schooling
    'fem_below24_married_before18',  # early marriage
    'fem_15_19_pregnant',  # teen pregnancy
    'fp_pill',  # contraceptive use
    'wom_preg_15_49_anaemic'  # anaemia
]

Xw = df[features_empower].dropna()
scaler = StandardScaler()
Xw_scaled = scaler.fit_transform(Xw)

# find best k
sil = {}
for k in range(2,7):
    km = KMeans(n_clusters=k, random_state=42, n_init=20)
    labels = km.fit_predict(Xw_scaled)
    sil[k] = silhouette_score(Xw_scaled, labels)
print("Silhouette scores:", sil)
best_k = max(sil, key=sil.get)
print("Best k:", best_k)

# final clustering
kmeans_w = KMeans(n_clusters=best_k, random_state=42, n_init=30)
labels_w = kmeans_w.fit_predict(Xw_scaled)
Xw['cluster'] = labels_w

# visualize PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=2, random_state=42)
Xw_pca = pca.fit_transform(Xw_scaled)

plt.figure(figsize=(7,6))
plt.scatter(Xw_pca[:,0], Xw_pca[:,1], c=labels_w, cmap='viridis', alpha=0.7)
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.title('Women’s Health & Empowerment Clusters')
plt.colorbar(label='Cluster')
plt.show()

# cluster centers
centers = pd.DataFrame(scaler.inverse_transform(kmeans_w.cluster_centers_), columns=features_empower)
print("Cluster Centers:\n", centers.round(2))

"""#DECISION TREE REGRESSOR"""

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.metrics import r2_score, mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Choose predictors based on previous analysis
features = [
    'fem_below24_married_before18',
    'fp_pill',
    'pop_below_15',
    'child_5_underweight',
    'wom_preg_15_49_anaemic',
    'pop_f_6_sch'
]

target = 'fem_15_19_pregnant'

# Clean data
X = df[features].dropna()
y = df.loc[X.index, target]

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeRegressor(max_depth=4, random_state=42)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("📈 Decision Tree Regression Results")
print(f"R² Score: {r2:.3f}")
print(f"RMSE: {rmse:.3f}")

plt.figure(figsize=(16,8))
plot_tree(model, feature_names=features, filled=True, rounded=True)
plt.title("Decision Tree Regressor for Teen Pregnancy Prediction")
plt.show()

imp = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(7,4))
sns.barplot(x='Importance', y='Feature', data=imp, palette='viridis')
plt.title("Feature Importance in Teen Pregnancy Prediction")
plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("Random Forest R²:", r2_score(y_test, y_pred_rf))

"""#DECISION TREE"""

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.metrics import r2_score, mean_squared_error
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Define predictors and target
features = [
    'pop_f_6_sch',               # Female education
    'fem_below24_married_before18',  # Early marriage
    'fem_15_19_pregnant',        # Teenage pregnancy
    'wom_preg_15_49_anaemic',    # Women anaemia
    'fp_pill',                   # Family planning (pill use)
    'pop_below_15'               # Child population
]
target = 'child_5_underweight'

# Drop missing values
X = df[features].dropna()
y = df.loc[X.index, target]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model_child = DecisionTreeRegressor(max_depth=4, random_state=42)
model_child.fit(X_train, y_train)

# Predictions
y_pred_child = model_child.predict(X_test)

# Evaluation
r2_child = r2_score(y_test, y_pred_child)
rmse_child = np.sqrt(mean_squared_error(y_test, y_pred_child))

print("📊 Decision Tree – Child Malnutrition")
print(f"R² Score: {r2_child:.3f}")
print(f"RMSE: {rmse_child:.3f}")

plt.figure(figsize=(16,8))
plot_tree(model_child, feature_names=features, filled=True, rounded=True)
plt.title("Decision Tree for Predicting Child Malnutrition")
plt.show()

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(24, 14), dpi=200)  # ⬅️ Larger size + high resolution
plot_tree(
    model_child,
    feature_names=features,
    filled=True,
    rounded=True,
    fontsize=10
)
plt.title("Decision Tree for Predicting Child Malnutrition", fontsize=16)
plt.show()

imp_child = pd.DataFrame({
    'Feature': features,
    'Importance': model_child.feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(7,4))
sns.barplot(x='Importance', y='Feature', data=imp_child, palette='crest')
plt.title("Feature Importance – Child Malnutrition Prediction")
plt.tight_layout()
plt.show()

imp_child

"""#LOGISTIC REGRESSION"""

df['high_bp_risk'] = (df['men_bp_sev'] > df['men_bp_sev'].median()).astype(int)

features = [
    'tobaco_men_15',
    'alcohol_men_15',
    'tobaco_women_15',
    'alcohol_women_15',
    'oral_cancer',
    'cerv_cancer'
]
target = 'high_bp_risk'

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Drop missing rows
X = df[features].dropna()
y = df.loc[X.index, target]

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

# Predict
y_pred = log_model.predict(X_test)

# Evaluate
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("📈 Logistic Regression – Men’s High BP Risk")
print(f"Accuracy: {acc:.3f}")
print(classification_report(y_test, y_pred))

# Confusion matrix
sns.heatmap(cm, annot=True, fmt='d', cmap='crest')
plt.title("Confusion Matrix – High vs Low BP Risk")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()